server:
  port: 9097

spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      host: localhost
      port: 27017
      database: project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9761/eureka/
  instance:
    hostname: localhost
